<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inventoryTab</name>
   <tag></tag>
   <elementGuidId>2edc9cff-d9ef-4fde-900a-e69552bbbe93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//a[contains((.),&quot;Inventory&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
