<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextButton</name>
   <tag></tag>
   <elementGuidId>792cc55b-3a82-4a48-b1b3-80be07f9eadc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//button[contains((.),&quot;Next&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
