<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_CUSTOMER ORDER REPORT</name>
   <tag></tag>
   <elementGuidId>8e76858c-026c-462e-ae75-ed67309ca839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.page-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>004ff62b-c58e-464b-988b-6bcf0bee58de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-heading</value>
      <webElementGuid>0b81288c-1d44-4005-92a4-fb1e0c162a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CUSTOMER ORDER REPORT</value>
      <webElementGuid>d9055a09-d249-45cc-847d-3b01c92490ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-md m-none bg-gray-lightest&quot;]/h1[@class=&quot;page-heading&quot;]</value>
      <webElementGuid>5a3184de-d46d-4718-aa79-da7ac51e92bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Report/CustomerOrderReport/Page_/iframe_content</value>
      <webElementGuid>245ab938-cf73-414a-b3e3-e586813e35c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>8a32226d-60ac-45dd-94da-daec9b7d879a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'CUSTOMER ORDER REPORT' or . = 'CUSTOMER ORDER REPORT')]</value>
      <webElementGuid>f4279264-9bf2-42a6-b205-d345e3b99cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
