<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Internal Billing Code</name>
   <tag></tag>
   <elementGuidId>4a15671f-ae02-49c9-9c0e-1b7f8e35dc3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.db > div:nth-of-type(28) > a.db.px-sm.py-xs.td-none.gray-dark.hov-bg-primary.hov-white.main-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='showSidebar']/div/div/div/nav/div/div/nav/div[3]/div/nav/div[28]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4f66b71-e23e-41ad-99c4-3e4b3ea548d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>db px-sm py-xs td-none gray-dark hov-bg-primary hov-white main-menu</value>
      <webElementGuid>7c20ab4f-e347-48c7-b6f6-99df359707ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>c9fa90b9-b59d-4ea4-8762-17204775c428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/meds/dme/production/data-setup/internal-billing-code/internal_billing_code.jsp</value>
      <webElementGuid>21ba3820-a6fa-4819-9189-ec9eb6753b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>cdeef196-4ffe-4922-8244-464730bd800e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Internal Billing Code</value>
      <webElementGuid>728e4a00-bc23-42c1-9bb3-f53c5dc052e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showSidebar&quot;)/div[@class=&quot;sidebar-placeholder&quot;]/div[1]/div[1]/nav[@class=&quot;pb-lg&quot;]/div[1]/div[1]/nav[1]/div[3]/div[1]/nav[@class=&quot;db&quot;]/div[28]/a[@class=&quot;db px-sm py-xs td-none gray-dark hov-bg-primary hov-white main-menu&quot;]</value>
      <webElementGuid>7c4383da-5391-42c9-ad2e-1ebe596ab202</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSidebar']/div/div/div/nav/div/div/nav/div[3]/div/nav/div[28]/a</value>
      <webElementGuid>654449a7-94ed-4f8a-af9e-35375ef5814c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Internal Billing Code')]</value>
      <webElementGuid>7c4ca34c-a053-46e2-8462-7a6bf49fd871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/meds/dme/production/data-setup/internal-billing-code/internal_billing_code.jsp')]</value>
      <webElementGuid>4bcf0c2e-a794-40f0-95e4-7e303fe5c19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/nav/div[28]/a</value>
      <webElementGuid>9f215159-8872-4c70-b476-2208c15adb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/meds/dme/production/data-setup/internal-billing-code/internal_billing_code.jsp' and (text() = 'Internal Billing Code' or . = 'Internal Billing Code')]</value>
      <webElementGuid>707b5c03-cad1-4a4a-9b26-9ade7f9fe853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
