<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_modify</name>
   <tag></tag>
   <elementGuidId>0477e1a7-0f4d-4dc6-b926-43bfdc9b26bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@onclick,'update')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f5bb68f-b138-4087-9bba-ada2e26cacb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>updateCode(&quot;IBC429&quot;, &quot;1&quot;, &quot;BONAFIDE QA TEST INTERNAL BILLING CODE&quot;)</value>
      <webElementGuid>fd8567d2-e58d-4d6d-bcbb-2b2356578297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>modify</value>
      <webElementGuid>0bb2c289-3846-4741-9f50-a93fed869a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hcpcsins&quot;)/tr[2]/td[@class=&quot;solid0&quot;]/span[1]/a[1]</value>
      <webElementGuid>d0bbb911-019e-43b2-b7b5-ec73d1e3a2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/InternalBillingCode/Page_/iframe_Eligibility_content</value>
      <webElementGuid>821848be-0b40-4584-9504-d3be4153267b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='updateCode(&quot;IBC429&quot;, &quot;1&quot;, &quot;BONAFIDE QA TEST INTERNAL BILLING CODE&quot;)']</value>
      <webElementGuid>69d3fe4f-4e6c-4d49-8bf9-5a89ebd04e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='hcpcsins']/tr[2]/td[4]/span/a</value>
      <webElementGuid>f0b43684-4a45-4a41-b34d-fb5cfc565ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'modify')]</value>
      <webElementGuid>b61a092e-8d33-47c9-8979-dbbee3ea8ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>2c1e2e9e-36ca-4043-893c-aadc1808a93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'modify' or . = 'modify')]</value>
      <webElementGuid>1937e14d-82b6-4c0f-9078-17aef8901677</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
