<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_srch_description</name>
   <tag></tag>
   <elementGuidId>f0bfb476-0b85-48ae-bc6a-feefcab96abd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#srch-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='srch-description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01cfb24a-f22a-401e-af1e-677abbdfd2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1bbae2e-fe98-4aa6-b151-54615bc32e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input-sm</value>
      <webElementGuid>393ac7eb-782a-4328-a34c-d6a44abf33c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>srch-description</value>
      <webElementGuid>3d9beb1f-b32e-433a-a9a2-1ca7734b822d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>srch_description</value>
      <webElementGuid>dcf6ba47-b451-439f-8793-19a491f3f248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>0f6dcd51-a439-4b6c-84e0-b1b4df723b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;srch-description&quot;)</value>
      <webElementGuid>ef204155-bba5-402d-aca6-4ada4eb4cffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/InternalBillingCode/Page_/iframe_Eligibility_content</value>
      <webElementGuid>bf5e7f86-9156-4d4a-b285-35f826f99a77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='srch-description']</value>
      <webElementGuid>56002378-8dee-45b6-b6a6-6bf32ebc70d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>147c9dda-1aa7-45f1-8a3e-074c336ce39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'srch-description' and @name = 'srch_description' and @placeholder = 'Description']</value>
      <webElementGuid>99ae3c46-cd63-43c0-9670-e64660e99f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
