<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_INVENTORY STOCK REPORT</name>
   <tag></tag>
   <elementGuidId>f265ba00-2ba2-453b-9fb1-9d1bf882fd8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ariCtrBld.colorBlu.size18.alignCtr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1500c44e-e094-4462-be19-17809a10251d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ariCtrBld colorBlu size18 alignCtr</value>
      <webElementGuid>b61f2580-29bd-435c-b530-0066e23a4873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>98577ec8-3b94-4327-a4fc-0eebe683b440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>a3ec50bf-dbfb-44fd-97d9-56e19c398b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>c55b69cd-f92f-4a72-8cf8-1502c0fe2365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>b3be1ddf-8156-4e79-b4f0-93ce48c119ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INVENTORY STOCK REPORT</value>
      <webElementGuid>b11444d2-ae40-4825-9652-6253ff4260e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/form[1]/div[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[3]/td[@class=&quot;ariCtrBld colorBlu size18 alignCtr&quot;]</value>
      <webElementGuid>28a16799-01ae-4e06-9d14-c601ad3f7924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>60f3454d-8eda-45c4-9b3d-c68356746f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'INVENTORY STOCK REPORT' or . = 'INVENTORY STOCK REPORT')]</value>
      <webElementGuid>19470201-715c-4a2a-942a-5867ebd8ec48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
