<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company_COMPANYNO</name>
   <tag></tag>
   <elementGuidId>7a1a6031-48a7-4579-bffe-c34d21b19e47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;COMPANYNO&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='COMPANYNO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3221e76-88f6-4171-976a-5e9336d7c2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eda22dc8-8c68-4aef-b49d-4ac6d06d3818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>COMPANYNO</value>
      <webElementGuid>c1e59dfa-2cb2-41c3-9d9c-a972c8b81596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>6b2d9d53-aba2-4da1-9f8f-d29189fba49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>eb4def91-27aa-44ff-9f78-ff2c18001a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c4ed6e32-9545-4e16-ba9a-1668d73296b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bodyNoMargin&quot;]/center[1]/table[3]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[2]/td[@class=&quot;pwloginEl&quot;]/table[1]/tbody[1]/tr[2]/td[2]/input[1]</value>
      <webElementGuid>a389bd08-c3e5-4614-8e25-961465bd92f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='COMPANYNO']</value>
      <webElementGuid>a3764909-e675-418d-9461-e07385e9c5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>a56d597c-0f4a-43a3-a98e-5a9b42887f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'COMPANYNO']</value>
      <webElementGuid>a5c2a037-e2c2-4cae-b032-e7aa73d43b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
