<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do not remember my company and employ_cd6edf</name>
   <tag></tag>
   <elementGuidId>5b383b7d-1818-4d95-b05e-f0152739ced7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navigation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='navigation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd5e83ab-2f30-4d20-8d27-2fd6f6cacc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6d59dbfb-264e-4148-b11f-9e90955fda52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signIn</value>
      <webElementGuid>76165901-ec87-4a19-92b9-1b7e3183bd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navigation</value>
      <webElementGuid>8890c69a-3090-4c0e-940c-5a6d7a1ecd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verBlackBold11</value>
      <webElementGuid>3b64bb83-e4d6-4f23-ae5a-a0b900b240c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>75691bc7-61ec-453c-8a4f-cfddef844040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation&quot;)</value>
      <webElementGuid>83f37e2f-c58d-4019-bc2c-bb83d1aba1b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='navigation']</value>
      <webElementGuid>52241a0b-6c04-4691-9592-560d102a476d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/input</value>
      <webElementGuid>4eec9fbe-6293-47ed-8067-c3392c18d16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'signIn' and @id = 'navigation']</value>
      <webElementGuid>34f4ada6-29c7-4ef1-a9d4-e1ee98248a3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
