<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MANIFEST ID_button button-xs button-info button-outline mr-xs</name>
   <tag></tag>
   <elementGuidId>3bb9c069-8ec1-499d-bb95-29d89f4d3c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='PRINT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28c40a60-55df-4224-a1fc-931dfa8432a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63e11658-9101-4e14-8810-431a81580412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-xs button-info button-outline mr-xs</value>
      <webElementGuid>75fe31d2-a4a2-459c-b78a-d985aa86bd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PRINT</value>
      <webElementGuid>e15f2b6a-cfab-436c-9295-655dfa978098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>f1()</value>
      <webElementGuid>2c755311-1646-4cdd-93bb-962e31c88686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-md m-none bg-gray-lightest&quot;]/form[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[34]/td[@class=&quot;right&quot;]/input[@class=&quot;button button-xs button-info button-outline mr-xs&quot;]</value>
      <webElementGuid>d436ab09-160c-498f-8460-7b975fe90d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Report/New_InventoryStockReport(New)/Page_/iframe_Eligibility_content</value>
      <webElementGuid>2fc4d778-6bf3-4a7f-bb9b-7b8dc2f14835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='PRINT']</value>
      <webElementGuid>903c0b47-0c97-4486-b2ff-e9e3e588828b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[34]/td/input[2]</value>
      <webElementGuid>b1afc766-8f9d-48a9-a49d-c97b970a8138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>78b1c0e9-b8bb-41e1-bec6-af248d848d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
