<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reports</name>
   <tag></tag>
   <elementGuidId>d31464aa-9090-41da-9ced-be65d59fa461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='showSidebar']/div/div/div/nav/div/div/nav/div[14]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.df.ai-center.bg-primary > a.px-sm.py-xs.td-none.fg-1.c-pointer.hov-white.main-menu.white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a2ed037-3d9d-4c86-9fff-01f05eec7be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>0f6479e3-8862-4436-a1ad-a6607f453637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/meds/servlet/com.meds.rpt.servlet.RptMain</value>
      <webElementGuid>c86a41a4-5a27-4e1d-9a4b-c1590d10edb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-sm py-xs td-none fg-1 c-pointer hov-white main-menu white</value>
      <webElementGuid>6170fab9-2074-41f1-83e3-1e7bb6dc0301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>054a73eb-6d1e-4971-b303-b1cbc35be3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>3330ae80-1858-4e2b-acd6-8d4498484856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showSidebar&quot;)/div[@class=&quot;sidebar-placeholder&quot;]/div[1]/div[1]/nav[@class=&quot;pb-lg&quot;]/div[1]/div[1]/nav[1]/div[14]/div[1]/div[@class=&quot;df ai-center bg-primary&quot;]/a[@class=&quot;px-sm py-xs td-none fg-1 c-pointer hov-white main-menu white&quot;]</value>
      <webElementGuid>9e7d3439-c8ff-4ef5-882a-b54c562f59a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSidebar']/div/div/div/nav/div/div/nav/div[14]/div/div/a</value>
      <webElementGuid>84b8a211-d7bd-4d58-ac24-522126459018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reports')]</value>
      <webElementGuid>ff65aed1-55f3-4543-951a-57cc7ab63ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/meds/servlet/com.meds.rpt.servlet.RptMain')]</value>
      <webElementGuid>85597d15-f8a2-4848-8d30-63e850790f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/a</value>
      <webElementGuid>548fc211-6165-4392-95af-183c2039a409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/meds/servlet/com.meds.rpt.servlet.RptMain' and (text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>78ca20d0-a677-4429-ab75-1828b39b9bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
