<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtSku</name>
   <tag></tag>
   <elementGuidId>056fb71e-df8c-4290-973d-13679c673e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txtSku']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtSku&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4138457a-985b-479d-8949-8562d72c8b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db47f37c-7440-47db-856e-cb78d71fe40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8637635a-d829-416f-b97b-618506747672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a4c54be8-b739-44f1-9517-7b036573b500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSku</value>
      <webElementGuid>67336ae9-4e6b-4c4e-acff-5b3e33a78f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input-sm ariBlkLft11</value>
      <webElementGuid>ee37efd0-711e-4ab6-a4c8-7ed400756b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>skuMask(this)</value>
      <webElementGuid>ac89cb3f-d773-497c-b4e1-80bf7776098f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblReport&quot;)/tbody[1]/tr[4]/td[2]/input[@class=&quot;input input-sm ariBlkLft11&quot;]</value>
      <webElementGuid>62beef59-e130-4c75-9b21-eee91792083b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Report/InventoryStockReport/Page_/iframe_content</value>
      <webElementGuid>c2473f1b-ff06-498b-be23-14d7ff351744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtSku']</value>
      <webElementGuid>4a791e76-a373-4b59-94bf-c08d74bbf3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblReport']/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>675eedbc-fce8-4c1c-9353-495d85775f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>787bb0c7-64e1-413b-b731-b3995db78570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtSku']</value>
      <webElementGuid>fc28add2-177e-4e60-9abc-b56649334ce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
