<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>VUOM</description>
   <name>VUOM</name>
   <tag></tag>
   <elementGuidId>2bff12ce-36d8-4221-8c1e-5ecf09736990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='vuom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
