<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ModifierCodes</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0d840514-71b3-4bde-9712-afadbb26edf8</testSuiteGuid>
   <testCaseLink>
      <guid>3de6055b-3ea4-4c45-8786-ca82abb58478</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/loginToApplication</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5513edcb-cd69-4809-8d7c-fef9cab76495</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/customerInfo</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5513edcb-cd69-4809-8d7c-fef9cab76495</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company Name</value>
         <variableId>a913aea1-8ff7-4421-beed-2bb0c1d1ab4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5513edcb-cd69-4809-8d7c-fef9cab76495</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserID</value>
         <variableId>534abf88-2c23-4bd6-b701-dfc5f691a1da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5513edcb-cd69-4809-8d7c-fef9cab76495</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>e7073a79-63c6-40e3-9649-3362b9abb996</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d66f37c1-a4e5-42e1-a799-86fb1a577dcf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Setup/Modifier Codes/Modifier Codes</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e187d2b5-1ac0-4ce7-8566-710c2cdc376b</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/dataSetup</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e187d2b5-1ac0-4ce7-8566-710c2cdc376b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Modifier Code</value>
         <variableId>3b4a8c12-ac6c-4566-b786-1298b71ac55a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e187d2b5-1ac0-4ce7-8566-710c2cdc376b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Description</value>
         <variableId>9f623bc1-25fd-49bd-8623-e4088f18f190</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>561330d4-2941-4b39-86f1-11b051ff9d50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5862d804-cdd7-4d5f-aa71-098d3163d60e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec8d9d2a-ff5d-4235-8415-c9d2ef786652</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
