<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inventory</name>
   <tag></tag>
   <elementGuidId>5bbec32b-71f0-4f21-8ee5-edd1aa828b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//a[contains(@href,&quot;.InvMain&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
