<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quickSearchButton</name>
   <tag></tag>
   <elementGuidId>19762e27-2ab1-48dd-a87a-9e9528559159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@name=&quot;formPOQuickSearch&quot;]//..//a[contains((.),&quot;Search&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
