<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_INVENTORY STOCK REPORT</name>
   <tag></tag>
   <elementGuidId>f8326b47-a44f-40ed-8b91-832971582542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/table/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ariCtrBld.colorBlu.size18.alignCtr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>57012094-2352-4a87-b16e-14a8ed6554e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ariCtrBld colorBlu size18 alignCtr</value>
      <webElementGuid>aec80c61-41f7-419e-bb1e-ee815a6a04f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6d6472e1-6932-47cf-8d7c-6a95a6c20f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>8231204a-c401-436e-a268-6db1248cab43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>77c08668-32f8-46a5-b381-590bd940da64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>31880363-7bb0-4b79-be08-1a2cd57e89fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INVENTORY STOCK REPORT</value>
      <webElementGuid>9255509e-8047-4e2e-9568-a03db6bf78e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/center[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[1]/td[@class=&quot;hd&quot;]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[2]/td[@class=&quot;ariCtrBld colorBlu size18 alignCtr&quot;]</value>
      <webElementGuid>108ef359-2b98-4c54-8efe-a0d315fc801c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td</value>
      <webElementGuid>eb22607a-02a5-4ec9-a412-9a82ed6ccc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'INVENTORY STOCK REPORT' or . = 'INVENTORY STOCK REPORT')]</value>
      <webElementGuid>a26b9686-0739-4333-ae58-04127c2a33b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
