<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ToBLR, Bengaluru International Airport _dbd09a</name>
   <tag></tag>
   <elementGuidId>372ef6c4-196a-416f-8681-2be27bb84988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fsw_inputBox.searchToCity.inactiveWidget.activeWidget</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>100c33ee-affa-442f-9cc8-7738e45d264f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fsw_inputBox searchToCity inactiveWidget activeWidget</value>
      <webElementGuid>4d3b3be0-a481-4078-99fe-7c70d5f23418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToBLR, Bengaluru International Airport IndiaPOPULAR CITIESMumbai, India Chhatrapati Shivaji International AirportBOMNew Delhi, India Indira Gandhi International AirportDELBangkok, Thailand BangkokBKKBengaluru, India Bengaluru International AirportBLRPune, India Pune AirportPNQHyderabad, India Rajiv Gandhi International AirportHYDKolkata, India Netaji Subhash Chandra Bose International AirportCCUChennai, India Chennai International AirportMAAGoa - Dabolim Airport, India Goa Dabolim International AirportGOIDubai, United Arab Emirates Dubai InternationalDXBNEWPlanning an international holiday?Not sure where to go? We can help!</value>
      <webElementGuid>99e680b3-2b82-413a-855a-1a60bc5f6889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bgGradient webpSupport landingPageBg&quot;]/div[@class=&quot;minContainer&quot;]/div[1]/div[@class=&quot;widgetSection appendBottom40 primaryTraveler&quot;]/div[@class=&quot;fsw widgetOpen&quot;]/div[@class=&quot;fsw_inner returnPersuasion&quot;]/div[@class=&quot;fsw_inputBox searchToCity inactiveWidget activeWidget&quot;]</value>
      <webElementGuid>e10ade6b-8c06-48d5-aca8-aa1b27b73129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>4c038566-bc72-4377-81c6-e8693decaba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEL, Delhi Airport India'])[1]/following::div[1]</value>
      <webElementGuid>077a0c47-a31f-4565-821a-11f44bd139e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/following::div[1]</value>
      <webElementGuid>663d4ea2-5a51-4a59-a073-6028cd954b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>e5c7cf93-ae7f-40bb-a847-50bcd4e3d2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ToBLR, Bengaluru International Airport IndiaPOPULAR CITIESMumbai, India Chhatrapati Shivaji International AirportBOMNew Delhi, India Indira Gandhi International AirportDELBangkok, Thailand BangkokBKKBengaluru, India Bengaluru International AirportBLRPune, India Pune AirportPNQHyderabad, India Rajiv Gandhi International AirportHYDKolkata, India Netaji Subhash Chandra Bose International AirportCCUChennai, India Chennai International AirportMAAGoa - Dabolim Airport, India Goa Dabolim International AirportGOIDubai, United Arab Emirates Dubai InternationalDXBNEWPlanning an international holiday?Not sure where to go? We can help!' or . = 'ToBLR, Bengaluru International Airport IndiaPOPULAR CITIESMumbai, India Chhatrapati Shivaji International AirportBOMNew Delhi, India Indira Gandhi International AirportDELBangkok, Thailand BangkokBKKBengaluru, India Bengaluru International AirportBLRPune, India Pune AirportPNQHyderabad, India Rajiv Gandhi International AirportHYDKolkata, India Netaji Subhash Chandra Bose International AirportCCUChennai, India Chennai International AirportMAAGoa - Dabolim Airport, India Goa Dabolim International AirportGOIDubai, United Arab Emirates Dubai InternationalDXBNEWPlanning an international holiday?Not sure where to go? We can help!')]</value>
      <webElementGuid>4d06315d-005e-4acc-8ff9-dda79dd2a499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
