<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BLR, Bengaluru International Airport _adb91c</name>
   <tag></tag>
   <elementGuidId>b3be6580-13ad-4a7c-9918-38bf61165456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.react-autosuggest__input.react-autosuggest__input--open.react-autosuggest__input--focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae69d0f7-6bcf-43b0-9876-03ac51733906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>defca417-c3cc-4a20-9c6f-8afdf33206e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6d87e73e-5724-4661-8648-9bd7f9f6d300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>211d9c90-194a-439c-9060-069fbb3531bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>react-autowhatever-1</value>
      <webElementGuid>03783667-7bf4-42e1-916e-9d4f3a7fdfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-autosuggest__input react-autosuggest__input--open react-autosuggest__input--focused</value>
      <webElementGuid>f88caca9-e744-4140-b6c2-a1a347395d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>To</value>
      <webElementGuid>2f23be0c-b6b4-43e9-8b3a-275bc1d60b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>df0ffec0-0166-4c33-9003-3cefc42f4f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bgGradient webpSupport landingPageBg&quot;]/div[@class=&quot;minContainer&quot;]/div[1]/div[@class=&quot;widgetSection appendBottom40 primaryTraveler&quot;]/div[@class=&quot;fsw widgetOpen&quot;]/div[@class=&quot;fsw_inner returnPersuasion&quot;]/div[@class=&quot;fsw_inputBox searchToCity inactiveWidget activeWidget&quot;]/div[1]/div[1]/div[@class=&quot;hsw_autocomplePopup autoSuggestPlugin makeFlex column spaceBetween&quot;]/div[@class=&quot;react-autosuggest__container react-autosuggest__container--open&quot;]/input[@class=&quot;react-autosuggest__input react-autosuggest__input--open react-autosuggest__input--focused&quot;]</value>
      <webElementGuid>4d3cdfca-44c7-45d2-8499-7b35f2dd9b0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='c']</value>
      <webElementGuid>7bc9b733-595e-49c4-9187-4ad8ceb6167f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>8cd49956-d9e3-4538-9670-aef9094d51c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>cb4e02e2-9776-4ef4-ad71-7999289a7a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'To']</value>
      <webElementGuid>d93a636b-043d-45a1-8fc7-3b22a156ae7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
