<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rs5000_ic_circularclose_grey</name>
   <tag></tag>
   <elementGuidId>366b9cfd-8128-4f83-bfb8-648f6b658339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ic_circularclose_grey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b65c0594-2bc7-4670-a1a6-32541712f1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic_circularclose_grey</value>
      <webElementGuid>e792a1ff-fd0e-4d3c-ba2d-f229eb8e2346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>handleSnackbarClose</value>
      <webElementGuid>8917fa2d-a1b2-4717-a809-f6bbe7c4e394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bgGradient webpSupport landingPageBg&quot;]/div[@class=&quot;appDnldCnt downloadAppToast makeFlex hrtlCenter&quot;]/div[@class=&quot;makeFlex column appendLeft20&quot;]/div[@class=&quot;makeFlex noShrink appendRight30&quot;]/span[@class=&quot;ic_circularclose_grey&quot;]</value>
      <webElementGuid>bc2509ab-ddfb-4c77-9108-096cffad0a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/span</value>
      <webElementGuid>9e44a80d-554a-45a3-8606-c60f82cb8eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/span</value>
      <webElementGuid>713c5f8c-b4ff-43bd-bd1a-18b2171b9b9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
