<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Office</name>
   <tag></tag>
   <elementGuidId>524a46b2-94cb-4900-a293-c8dc98c289c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/table/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.table.table-sm.w-100 > tbody > tr:nth-of-type(2) > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>03be3ff8-03db-464b-9bdd-1b85be0ccbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1%</value>
      <webElementGuid>709a1c57-5fad-494a-bcc3-f32b5b9577c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Office</value>
      <webElementGuid>a6b16ae1-fcde-4194-8e1e-47fedcb1b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-md m-none bg-gray-lightest&quot;]/form[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[1]/table[@class=&quot;table table-sm w-100&quot;]/tbody[1]/tr[2]/td[1]</value>
      <webElementGuid>d88f2a3a-5def-4774-854d-4ccafb943ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Report/New_AgingReport(new)/Page_/iframe_Eligibility_content</value>
      <webElementGuid>aea8eac0-b9f4-4281-8d8f-421a01db63cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td</value>
      <webElementGuid>edc447d8-4850-4a43-a348-a61fa5f21894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Office' or . = 'Office')]</value>
      <webElementGuid>849782a9-8dfc-495b-bf01-4c85b5f5b316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
