<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_taskId</name>
   <tag></tag>
   <elementGuidId>9cac1311-c31d-4aef-8b15-3686d2afa149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='taskId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;taskId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4bc1b81-26f5-436d-a7ea-b337cc6469cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a76b0708-7a2b-45c0-90f1-262fca4dcffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>taskId</value>
      <webElementGuid>a6b73958-eaab-403f-a27b-d5a963295e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kds</value>
      <webElementGuid>ba35ea83-10c2-4c9a-b064-363b2cde41ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ee444fa1-d003-4505-a8f2-a6e437e85a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search&quot;)/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[@class=&quot;sub&quot;]/td[@class=&quot;input&quot;]/input[@class=&quot;kds&quot;]</value>
      <webElementGuid>f90a7bf9-fa60-45db-962d-9bca4fcdc828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='taskId']</value>
      <webElementGuid>d3b38cd0-acb3-4546-9d13-fc1d83dc1f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='task-search']/tbody/tr[3]/td/table/tbody/tr[17]/td[2]/input</value>
      <webElementGuid>f161e7a2-3117-4d8a-a644-2511927314ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/input</value>
      <webElementGuid>02eaf390-732e-401e-82fc-b3d2b0ded85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'taskId']</value>
      <webElementGuid>082aa625-0754-4fad-9f9d-9cde7857ca5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
