<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_referenceNo</name>
   <tag></tag>
   <elementGuidId>874be313-80f3-4365-8f4b-4ea3523415e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='referenceNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;referenceNo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>272341a2-3f9c-4882-8944-6c0355ba64cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44c03bae-5804-4b2b-9bcd-e65bd1461a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>referenceNo</value>
      <webElementGuid>32b53dc2-e35b-4b4e-88f5-9f01b6a51197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2432d6a5-04dc-43e9-b404-b3eedc60bef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search&quot;)/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[@class=&quot;sub&quot;]/td[@class=&quot;input&quot;]/input[1]</value>
      <webElementGuid>09da26a7-13b6-4d7a-bca9-ed9dd3c6e580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='referenceNo']</value>
      <webElementGuid>0ad59cb9-2e00-4bea-9aba-33fcf7619cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='task-search']/tbody/tr[3]/td/table/tbody/tr[24]/td[2]/input</value>
      <webElementGuid>3eb085ca-a354-4b58-b3a5-1fc90cfa0b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[24]/td[2]/input</value>
      <webElementGuid>609814f4-9853-44d5-b1f3-c049d6f341fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'referenceNo']</value>
      <webElementGuid>ff767ff5-a6eb-4522-8ba4-1706020b2e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
