<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllOpenClosed</name>
   <tag></tag>
   <elementGuidId>1eb4b201-606f-44df-8d0d-2f66438a0c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='closingStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;closingStatus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2ed690fb-a4f3-4931-a797-8094a1141938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>closingStatus</value>
      <webElementGuid>5ff6a58e-c68e-4804-bfa0-bd297b33f48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllOpenClosed</value>
      <webElementGuid>5f80ddc1-b9fc-4c48-b7a9-c9babff517d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search&quot;)/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[14]/td[@class=&quot;input&quot;]/select[1]</value>
      <webElementGuid>2fab257b-c5ac-4dc5-a7bf-eb3fa13e8658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='closingStatus']</value>
      <webElementGuid>af9bd987-e7af-4af0-8298-50c8c76a99dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='task-search']/tbody/tr[3]/td/table/tbody/tr[14]/td[2]/select</value>
      <webElementGuid>03222a39-432c-4345-a472-99773f1ee284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/select</value>
      <webElementGuid>20ad19d6-ae85-4dea-a205-41f171f33168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'closingStatus' and (text() = 'AllOpenClosed' or . = 'AllOpenClosed')]</value>
      <webElementGuid>52ed2837-f411-4726-a9e2-f9d6678c8703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
