<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllIn ProgressAll DoneNot WorkingNot Me</name>
   <tag></tag>
   <elementGuidId>37d44a36-75e7-48ec-b765-896d455515ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='overallProgressStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;overallProgressStatus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>50368cd7-5cd5-4f59-8d60-49ab6f874c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>overallProgressStatus</value>
      <webElementGuid>4cfcaea5-fe9c-4804-80e8-9dcf73ee67ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllIn ProgressAll DoneNot WorkingNot Me</value>
      <webElementGuid>53feede4-08a2-4217-a3d1-cd081de55acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search&quot;)/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[14]/td[@class=&quot;input&quot;]/select[2]</value>
      <webElementGuid>89c1d4ad-de5c-49de-a62b-a51510e3ea8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='overallProgressStatus']</value>
      <webElementGuid>02de9db8-3911-4a79-b640-1916e0c28d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='task-search']/tbody/tr[3]/td/table/tbody/tr[14]/td[2]/select[2]</value>
      <webElementGuid>f79e0ff7-9db2-4a22-9a90-ff1e216d80fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/select[2]</value>
      <webElementGuid>bc7d12f6-997f-411e-a21d-9869cc7e45f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'overallProgressStatus' and (text() = 'AllIn ProgressAll DoneNot WorkingNot Me' or . = 'AllIn ProgressAll DoneNot WorkingNot Me')]</value>
      <webElementGuid>b150d1bb-e713-4edc-b751-e8c8f1159327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
