<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VUOM_vuom</name>
   <tag></tag>
   <elementGuidId>dc5ea7fc-b5a6-4a74-9999-390e9baca026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;vuom&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='vuom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a0dcc55-2f93-4a04-b3a6-f4a0f8a41f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e430801-fa21-4f18-bb9d-653eca2d2c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vuom</value>
      <webElementGuid>edd5aee1-3721-489b-a501-bddaabe580f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>solid1 height29 uppercase</value>
      <webElementGuid>afc67392-0272-4ae9-9665-f94a78ecb716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/form[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[@class=&quot;alignTop horiPad8 vertPad10&quot;]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[3]/td[2]/input[@class=&quot;solid1 height29 uppercase&quot;]</value>
      <webElementGuid>41763bb8-f882-4fe4-bfa0-648a37fce5c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='vuom']</value>
      <webElementGuid>a03088d0-a8b6-4b66-9f3b-75b2c059e3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>bd144161-b431-4776-9e3c-9ee73df7e0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vuom']</value>
      <webElementGuid>806ff4a5-f9be-49fd-a767-c38222ceb767</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
