<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EA                    BX            _7b3fc1</name>
   <tag></tag>
   <elementGuidId>569bdde9-3133-49be-a821-3449d2a442ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cuom&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cuom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5de4bd5b-0c8b-4b8a-a69a-93b553cbffb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cuom</value>
      <webElementGuid>88a3a08f-45d7-439a-9ef1-d9e254dbef7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>solid1 height29 uppercase</value>
      <webElementGuid>36235d73-03af-474f-a1d7-1d82f8ad11f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    EA
                    BX
                    CS
                    PK
                    PR
                </value>
      <webElementGuid>a566f3e1-e404-46eb-baea-b897dbe15cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/form[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[@class=&quot;alignTop horiPad8 vertPad10&quot;]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[4]/td[2]/select[@class=&quot;solid1 height29 uppercase&quot;]</value>
      <webElementGuid>66d1329e-f34b-4f5e-9e3d-d22411f919fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cuom']</value>
      <webElementGuid>943ca866-271d-465d-99fd-8025d0001b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c1886549-e82c-4c65-9dc1-2988d8e2ffb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cuom' and (text() = '
                    EA
                    BX
                    CS
                    PK
                    PR
                ' or . = '
                    EA
                    BX
                    CS
                    PK
                    PR
                ')]</value>
      <webElementGuid>c4c677a3-77c6-49b9-80c2-c1e8f6e07299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
