<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>nextStep1</description>
   <name>nextStep1</name>
   <tag></tag>
   <elementGuidId>f6914113-e3bc-4c38-a464-beffd67af20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
