<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Catalogno_catalogno</name>
   <tag></tag>
   <elementGuidId>8d386684-b932-49f6-a1d4-f3c394b1484f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='catalogno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;catalogno&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7046695-6305-4c13-83bc-e55bcec0f271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a39af960-78f7-4b84-9b24-16532e39c660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>catalogno</value>
      <webElementGuid>be516e1d-9f6b-48bd-814e-f6519c7b97f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>solid1 height29 uppercase</value>
      <webElementGuid>a76ccbda-3da0-4ffd-90f4-ee729a42fdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/form[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[@class=&quot;alignTop horiPad8 vertPad10&quot;]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[2]/td[2]/input[@class=&quot;solid1 height29 uppercase&quot;]</value>
      <webElementGuid>e464d707-ee26-4d30-8f3a-46693430294a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='catalogno']</value>
      <webElementGuid>42535e83-0596-4711-9a7a-185fa5d77483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>5a864a07-c107-4e9b-abeb-551b3c9ec4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'catalogno']</value>
      <webElementGuid>52bef63b-e86a-40ea-a345-29c2187faf9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
