<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Only YouAll Employees</name>
   <tag></tag>
   <elementGuidId>306e6468-d932-4d78-92bc-2a81406b8171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='viewingTarget']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;viewingTarget&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>59d6c30d-6963-476b-96b2-19bfe4f110e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>viewingTarget</value>
      <webElementGuid>589c34cb-35fb-41ce-ac1f-bcdbf722d639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Only YouAll Employees</value>
      <webElementGuid>4e71d9f2-d2a5-432b-a4f4-915b11a36ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search&quot;)/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[9]/td[@class=&quot;input&quot;]/select[1]</value>
      <webElementGuid>81c3f93f-5d9c-448e-aad6-984530f48ff0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='viewingTarget']</value>
      <webElementGuid>7ea2879c-199c-4481-9149-4c7625100f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='task-search']/tbody/tr[3]/td/table/tbody/tr[9]/td[2]/select</value>
      <webElementGuid>5060c598-000a-4213-b931-30966b1f4088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/select</value>
      <webElementGuid>75917f48-610f-44db-b5d7-2fc8e26bac0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'viewingTarget' and (text() = 'Only YouAll Employees' or . = 'Only YouAll Employees')]</value>
      <webElementGuid>57dfed74-4ec1-4376-8991-336bfaad51ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
