<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_164331</name>
   <tag></tag>
   <elementGuidId>ca1c34d5-3cd7-4830-b35a-e94ccdd3fa45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'164331')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot; **** &quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a2a60e9-7a2d-4c71-9bd7-8fd34754b7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> **** </value>
      <webElementGuid>15fd5a75-9c9a-4fe0-afab-c7d665dd268e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:getClaim('164331','')</value>
      <webElementGuid>cb490bd9-a081-461a-9798-b1850898cc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>164331 </value>
      <webElementGuid>d7b1ae7b-1fd0-41bb-a489-2f9fdaba13c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-md m-none bg-gray-lightest&quot;]/form[1]/div[@class=&quot;cf mb-lg&quot;]/div[@class=&quot;mt-md&quot;]/div[@class=&quot;fl w-80 pl-md&quot;]/div[2]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[1]/td[4]/a[1]</value>
      <webElementGuid>7189531a-52cd-4823-b3c3-2672fb48ba24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New_ClaimFiling/Page_/iframe_Eligibility_content (2)</value>
      <webElementGuid>1a676f6d-ce23-42a5-9e38-9ac5b1ff5b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'164331')]</value>
      <webElementGuid>a5e51f19-b93d-4ad8-9a4b-9aa6382c768a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:getClaim('164331','')&quot;)]</value>
      <webElementGuid>b61f773b-46e3-4755-a04b-069bb73762e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[4]/a</value>
      <webElementGuid>b8efe61b-8067-48e2-84af-ed3e4aaf5604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = ' **** ' and @href = concat(&quot;javascript:getClaim(&quot; , &quot;'&quot; , &quot;164331&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '164331 ' or . = '164331 ')]</value>
      <webElementGuid>b4c4be02-def7-4670-bf75-627fd608522f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
