<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Claim No_claimno</name>
   <tag></tag>
   <elementGuidId>027909d7-6de8-4c65-bc59-aec364710821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='claimno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;claimno&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f66c6e9d-0cde-4c26-8672-33db6866a93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b57f974-c673-4ca8-bd1f-1aeef97a6d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input-sm</value>
      <webElementGuid>20d3172f-814d-420a-9b02-322fee24d5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>claimno</value>
      <webElementGuid>f59df246-3081-465d-98f3-71b5b83c9db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>doSearchClaim(event)</value>
      <webElementGuid>0c8db970-196b-4949-b588-dc15301841f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>5b6448d2-19d7-4776-9d33-18e020ce8514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>percentMask(this);</value>
      <webElementGuid>3ee5715a-510f-4975-a019-949beeabaae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-md m-none bg-gray-lightest&quot;]/form[1]/div[@class=&quot;cf mb-lg&quot;]/div[@class=&quot;claim-search-form-placeholder&quot;]/div[@class=&quot;bs-1&quot;]/div[@class=&quot;panel&quot;]/div[@class=&quot;bg-white clearfix df&quot;]/div[@class=&quot;df fg-1&quot;]/table[@class=&quot;table table-sm w-100&quot;]/tbody[1]/tr[3]/td[4]/input[@class=&quot;input input-sm&quot;]</value>
      <webElementGuid>ef5f09bf-eef5-4123-95c0-bac8db9630fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New_ClaimFiling/Page_/iframe_Eligibility_content</value>
      <webElementGuid>bc9f7bbc-e363-4181-a65c-301d506a4d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='claimno']</value>
      <webElementGuid>75a48c77-0e59-4e78-91b9-752226ca5edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
      <webElementGuid>e404be11-b248-4c2f-988d-f936c689eaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'claimno']</value>
      <webElementGuid>05d927e0-f1cf-4714-b536-39f9795dcfcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
