<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_164331</name>
   <tag></tag>
   <elementGuidId>998e2eb0-4e76-4614-882b-c8a6361b225b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/table/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > table.table.table-sm > tbody > tr > td:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2f644b17-efad-4861-9562-9fc553df48df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bgcolor</name>
      <type>Main</type>
      <value>FFFFFF</value>
      <webElementGuid>89e5069a-5203-4a45-b58b-dccf25352a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>164331 </value>
      <webElementGuid>19bc51f7-bbc8-454b-832d-a6da6ec04d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-md m-none bg-gray-lightest&quot;]/form[1]/div[@class=&quot;cf mb-lg&quot;]/div[@class=&quot;mt-md&quot;]/div[@class=&quot;fl w-80 pl-md&quot;]/div[2]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>a8baaca3-db31-4f94-9c0c-7b36c38eccd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New_ClaimFiling/Page_/iframe_Eligibility_content (2)</value>
      <webElementGuid>e4f20a0a-bdec-4197-9d5b-629835110bbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[4]</value>
      <webElementGuid>54e64819-6d99-4cc4-83a9-dc0649091064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '164331 ' or . = '164331 ')]</value>
      <webElementGuid>8d09b89c-6530-47c7-99df-c3dc975bd14d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
