<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_PASSWORD</name>
   <tag></tag>
   <elementGuidId>1f6f76c5-8a5b-4fb0-8e9a-3bd04188ab23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;PASSWORD&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='PASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>544c069f-3346-4e15-b6ef-8a288ccfae44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a719f635-1210-4efe-ba80-f94b5e2ab692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PASSWORD</value>
      <webElementGuid>9a40cf43-f217-4cac-a6b6-0558b66dcbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>482ff5f4-800e-4574-bae9-bef8f7757de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce48b0a0-2534-4474-99e1-09ca74a62099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bodyNoMargin&quot;]/center[1]/table[3]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[2]/td[@class=&quot;pwloginEl&quot;]/table[1]/tbody[1]/tr[4]/td[2]/input[1]</value>
      <webElementGuid>60806c91-7798-4add-bf90-132f2d6b4b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='PASSWORD']</value>
      <webElementGuid>de229e25-9fe4-4ce3-9dce-962df9f94bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>d25c311a-3db8-4b31-89a6-6eaf69212e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'PASSWORD']</value>
      <webElementGuid>75d27973-00b3-46a2-a19d-1cbc6bdb3f0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
