<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do not remember my company and employ_cd6edf</name>
   <tag></tag>
   <elementGuidId>7ea9fd1c-a409-4bee-9438-99db03e56778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navigation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='navigation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efd6f3af-2e9f-400b-b725-7cc5303d2a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>501d7535-e063-47a4-8000-cb52edf8914d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signIn</value>
      <webElementGuid>e0702011-ff56-47bf-9c3c-e5965a4958f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navigation</value>
      <webElementGuid>f7c28671-3432-40f7-8615-addc9474cf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verBlackBold11</value>
      <webElementGuid>cef2c97a-c6b7-44aa-b9ab-ca2d0333b0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>6540aaa2-7a24-4de8-95e4-ddd3696a6e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation&quot;)</value>
      <webElementGuid>e5fb5bc2-ab77-4f0a-ad49-6b37304840e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='navigation']</value>
      <webElementGuid>59b6f4af-0b73-4d3f-a5c6-b2117fe8e3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/input</value>
      <webElementGuid>77774a40-0deb-4d1e-9ac9-6a10f6718fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'signIn' and @id = 'navigation']</value>
      <webElementGuid>7d70b99d-3d28-4d54-8429-17d0b351d254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
