<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CUSTOMER ORDER REPORT</name>
   <tag></tag>
   <elementGuidId>b3b230e6-f35d-457e-9db5-f189cfa88b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ariCtrBld.colorBlu.size18.alignCtr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7d6be596-dd1f-4995-9fbe-11b71cddeca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ariCtrBld colorBlu size18 alignCtr</value>
      <webElementGuid>1672bd8c-bb8b-470a-bba0-8eb298346028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9fc2e977-1c2f-4e2f-9099-87c436b769d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>8cfbc261-ebbf-4c11-bbfc-ca3366e92d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>5d01a00f-53b5-4aa6-8f97-2caf020a9a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>648a5973-a291-4e84-b49a-5915ade99930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CUSTOMER ORDER REPORT</value>
      <webElementGuid>ec1fca23-4ee1-4ca0-bd2c-42960e44eb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/center[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[3]/td[@class=&quot;ariCtrBld colorBlu size18 alignCtr&quot;]</value>
      <webElementGuid>0bf947d4-8ab1-42a2-8a57-178d1d282652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>6c601a87-4ad7-4141-a3de-82f307584d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CUSTOMER ORDER REPORT' or . = 'CUSTOMER ORDER REPORT')]</value>
      <webElementGuid>27093c50-77d6-4a22-a261-78f30451bada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
