<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BmsEdiId_bmsEdiId</name>
   <tag></tag>
   <elementGuidId>5a9565cc-a82d-4ced-b63c-b12dd11e8061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='bmsEdiId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;bmsEdiId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0893f18b-87ab-4a5b-8844-3f42eeb885aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c9c2830-f4ca-4db9-90c4-e284e9997bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>solid1 height29 uppercase</value>
      <webElementGuid>c4dbd841-eb73-451c-8ee2-04040153e84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bmsEdiId</value>
      <webElementGuid>aa0eea2c-3c38-4349-9e50-98d273171baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-gray-lightest&quot;]/form[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[1]/input[@class=&quot;solid1 height29 uppercase&quot;]</value>
      <webElementGuid>61c44aa8-42ba-44ed-b576-8bde395da598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Data Setup/OLUOM/Page_/iframe_Eligibility_content</value>
      <webElementGuid>b35fba5b-3c5b-4254-97f9-c34f55a2d005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='bmsEdiId']</value>
      <webElementGuid>9e6ca486-4bb3-4b82-a4fc-57315cd49c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e34cf533-4f94-42c7-a100-9e1a696e9368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bmsEdiId']</value>
      <webElementGuid>5e10c47d-dfd5-4a71-ac35-7ff64e77909f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
