<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_delete</name>
   <tag></tag>
   <elementGuidId>ecc6764f-34bf-4c79-b084-d88c7d43e9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52988198-e004-4068-a7ba-ccd327208fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:formOluomMain_DeleteItem('39284AFG', '793487DET', 'CX', 'BX');</value>
      <webElementGuid>426a023d-c348-4fc2-8d05-f5043b537a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>green clickButton</value>
      <webElementGuid>da7f12b1-ce5e-4c1a-941a-e0e76d99ed43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>fd079fc2-abb3-487e-98b5-f898e27ec3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-gray-lightest&quot;]/form[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[4]/td[@class=&quot;solidBlk1&quot;]/a[@class=&quot;green clickButton&quot;]</value>
      <webElementGuid>7b2ffe6d-feb9-4f92-a6c5-45b2738f29e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OLUOM1/Page_/iframe_Eligibility_content</value>
      <webElementGuid>83acc1dc-d001-455b-9f2d-544ddde2fa38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'delete')]</value>
      <webElementGuid>a42b30e2-4d7d-4fcd-b544-4631762b26b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:formOluomMain_DeleteItem('39284AFG', '793487DET', 'CX', 'BX');&quot;)]</value>
      <webElementGuid>5b9aeb11-3606-4dd3-99ee-62af347e6dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>1db1dd57-946e-45aa-9cad-5ff101f0b85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:formOluomMain_DeleteItem(&quot; , &quot;'&quot; , &quot;39284AFG&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;793487DET&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;CX&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;BX&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'delete' or . = 'delete')]</value>
      <webElementGuid>0665684c-359f-455d-a149-bb6c642b8c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
