<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_39284AFG</name>
   <tag></tag>
   <elementGuidId>32c17121-9ab4-42a6-89ec-a41f5368b525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.uppercase.green.clickButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3c3a46d-853f-472c-ab82-3e9ce318d3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uppercase green clickButton</value>
      <webElementGuid>d8f364c0-551b-4150-8f7a-1de6b54136c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>39284AFG
              </value>
      <webElementGuid>75ba98b4-1e65-49c8-bfb6-7378329654c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-gray-lightest&quot;]/form[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[4]/td[@class=&quot;solidBlk1 alignTop&quot;]/a[@class=&quot;green clickButton&quot;]/div[@class=&quot;uppercase green clickButton&quot;]</value>
      <webElementGuid>51d66364-a589-4457-9de1-450562e4c5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OLUOM1/Page_/iframe_Eligibility_content</value>
      <webElementGuid>c6134706-2b40-47da-8d55-8d06eddf592e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>fe6be250-a265-4130-acec-71abdc4580f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '39284AFG
              ' or . = '39284AFG
              ')]</value>
      <webElementGuid>2e3461aa-4e19-4394-9497-c6de716ecd54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
