<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BmsEdiId_bmsEdiId</name>
   <tag></tag>
   <elementGuidId>c3c014f8-d1c5-44f9-a4de-721860557cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;bmsEdiId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='bmsEdiId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77250dd6-eb20-4dbf-bc9c-ae0f3c8fd934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f0fbaf2-1d50-4502-92fe-3a747cb94278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>solid1 height29 uppercase</value>
      <webElementGuid>b224121e-0f32-4cd3-934d-15499f823d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bmsEdiId</value>
      <webElementGuid>1c2512c0-5f07-4e53-9d03-e03cc50ff660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-gray-lightest&quot;]/form[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[1]/input[@class=&quot;solid1 height29 uppercase&quot;]</value>
      <webElementGuid>aca07949-9d17-4702-9df2-114d8b1e494d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OLUOM1/Page_/iframe_Eligibility_content</value>
      <webElementGuid>f2e6e2fc-d302-4ff8-9e05-e96e498aeda3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='bmsEdiId']</value>
      <webElementGuid>737d89f7-3563-4f6c-bc4d-36cd7ceb993f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>45019218-1b9c-40b5-b904-005ec6891dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bmsEdiId']</value>
      <webElementGuid>8bb67b4d-a15d-4f5b-a8c1-04dafa9846d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
