<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>1d302df5-148c-4585-ace6-85e474aec040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='I am Sure']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4955453-bd22-4db3-80ec-70d5aa9454c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab2f65d2-e3ef-49d6-ae71-631501bf09d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I am Sure</value>
      <webElementGuid>4636ce69-41bc-4f98-9f8d-6e6ffa477de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>formDecision_Submit();</value>
      <webElementGuid>ea4e09f9-3d8a-4e24-b5f2-5660da6a3a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/form[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[3]/td[@class=&quot;topPad4 lftPad3 btmPad9 rgtPad9 alignTop&quot;]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[8]/td[@class=&quot;rgtPad5&quot;]/input[1]</value>
      <webElementGuid>e95913e7-3f6c-43f5-959d-73b9d51f04ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='I am Sure']</value>
      <webElementGuid>cb1e996e-6900-4a7f-81c1-597f1e2dbdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/input</value>
      <webElementGuid>febd8915-bec3-482f-8b10-65773153ffc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>e5fce6fa-5378-4281-8d6f-0af34ad1dc40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
