<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reports</name>
   <tag></tag>
   <elementGuidId>c885d94c-9f20-4bf4-8622-4bbe7dd26fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='showSidebar']/div/div/div/nav/div/div/nav/div[14]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.df.ai-center.bg-primary > a.px-sm.py-xs.td-none.fg-1.c-pointer.hov-white.main-menu.white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eaf11afe-b4fa-46b1-884c-e3c58a5a7115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>5cd21c7b-4541-4e7c-a87e-0a4c355cd59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/meds/servlet/com.meds.rpt.servlet.RptMain</value>
      <webElementGuid>dfcea0ec-1e73-4da5-b6cd-c25ef674766e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-sm py-xs td-none fg-1 c-pointer hov-white main-menu white</value>
      <webElementGuid>92bfe944-9215-4cc5-b319-824e80200fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>7848d71e-c492-47e9-b5bd-3fb7cb2f6f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>ad5b6452-7883-4950-b906-dbd3c217fef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showSidebar&quot;)/div[@class=&quot;sidebar-placeholder&quot;]/div[1]/div[1]/nav[@class=&quot;pb-lg&quot;]/div[1]/div[1]/nav[1]/div[14]/div[1]/div[@class=&quot;df ai-center bg-primary&quot;]/a[@class=&quot;px-sm py-xs td-none fg-1 c-pointer hov-white main-menu white&quot;]</value>
      <webElementGuid>dd2fd893-50a2-46ab-a6b2-6fab36663824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSidebar']/div/div/div/nav/div/div/nav/div[14]/div/div/a</value>
      <webElementGuid>ab39c3bc-b232-451a-a2ab-293e7d5095ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reports')]</value>
      <webElementGuid>0f18e34f-a6c6-4d57-80b6-874e21c4a65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/meds/servlet/com.meds.rpt.servlet.RptMain')]</value>
      <webElementGuid>5f395232-fa7b-4d3e-91a5-5ea0697e9d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/a</value>
      <webElementGuid>a6dae30f-50f6-472a-b17e-07e123698e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/meds/servlet/com.meds.rpt.servlet.RptMain' and (text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>669fe77c-0bd2-4661-8852-a19d221f545e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
