<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click              here</name>
   <tag></tag>
   <elementGuidId>3079f957-8e8a-4898-9a4d-499f590c01c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Click
              here')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.redYestoyes.green.clickButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e62cb571-6b26-49ed-8378-ad745548b0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:formOluomMain_AddNew();</value>
      <webElementGuid>634bc3f5-57e0-4ca8-a558-0f63e9f919fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>redYestoyes green clickButton</value>
      <webElementGuid>575fbce2-4804-40ca-8f7b-267f9edbabd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click
              here</value>
      <webElementGuid>92976b9e-2403-4da2-a40d-20f70d612871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-gray-lightest&quot;]/form[1]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[1]/a[@class=&quot;redYestoyes green clickButton&quot;]</value>
      <webElementGuid>46d5a6b1-ef14-41fa-82ea-52abd91f4b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Data Setup/OLUOM/Page_/Page_/iframe_Eligibility_content</value>
      <webElementGuid>a2c84d07-4db9-4b5c-94d6-a96253d120fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Click
              here')]</value>
      <webElementGuid>16ff2bb7-d8d3-4834-bcc6-c44d4123bc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BmsEdiId'])[1]/preceding::a[1]</value>
      <webElementGuid>81fb5a22-f96a-4a21-ae53-7aa634ab0593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:formOluomMain_AddNew();')]</value>
      <webElementGuid>3854043c-17ba-4a97-9a92-25e857cbb86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>c17a3328-7b34-47ea-8bd1-fd029afa2167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:formOluomMain_AddNew();' and (text() = 'Click
              here' or . = 'Click
              here')]</value>
      <webElementGuid>10d278bd-92ee-4164-92ff-3499e022c4a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
