<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VUOM_vuom</name>
   <tag></tag>
   <elementGuidId>5da86f96-5239-4dcc-841c-4d25342cea19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='vuom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;vuom&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca3afd1e-f9b8-42d8-92bd-cc9170d0dff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d993c12-59f6-44f7-91e3-536f5a002c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vuom</value>
      <webElementGuid>0a82892b-768e-4e3b-a26a-54fca01277ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>solid1 height29 uppercase</value>
      <webElementGuid>eb0d86d1-e44e-461a-90dc-c1661643a5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/form[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[@class=&quot;alignTop horiPad8 vertPad10&quot;]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[3]/td[2]/input[@class=&quot;solid1 height29 uppercase&quot;]</value>
      <webElementGuid>d94023d1-f990-4850-a76d-109a39430c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='vuom']</value>
      <webElementGuid>f8acc0eb-7601-4d48-86f4-a78f466edb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>9c112638-01a8-4dfc-be83-d4a687c6abb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vuom']</value>
      <webElementGuid>6cb5a76e-6c5e-47ac-a7a2-34b27373b7a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
