<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Catalogno_catalogno</name>
   <tag></tag>
   <elementGuidId>c39f58d1-f859-4830-8de8-c83a6b699c3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='catalogno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;catalogno&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbc9a880-79d1-47b6-9532-83b055d6a36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>318e8c80-862a-4f09-a439-89332aa19b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>catalogno</value>
      <webElementGuid>5aa23c92-839f-47ef-8229-eead91c4f7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>solid1 height29 uppercase</value>
      <webElementGuid>6a573b4e-7822-4058-b51e-ef8bb58fad10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/form[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[@class=&quot;alignTop horiPad8 vertPad10&quot;]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[2]/td[2]/input[@class=&quot;solid1 height29 uppercase&quot;]</value>
      <webElementGuid>eeb6f3b4-c7cb-440b-8797-26ee16935a3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='catalogno']</value>
      <webElementGuid>38832fcc-b765-4620-914f-c03faad8ebc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>e016a70e-e2e5-4e5e-b79e-499e8c32a5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'catalogno']</value>
      <webElementGuid>9b0d5a45-03f4-4652-a65d-97ae16d97efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
