<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BmsEdiId_bmsEdiId</name>
   <tag></tag>
   <elementGuidId>5cdb62df-3da0-40bc-83fd-df780a80ec2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='bmsEdiId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;bmsEdiId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9d0a0aa-4121-489b-8880-b6cfbb0e7c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed3e91ff-bae4-4d99-be70-9865663d296f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bmsEdiId</value>
      <webElementGuid>75790706-147d-444f-9ae5-066b5d2dfb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>solid1 height29 uppercase</value>
      <webElementGuid>c76f4e4c-b840-4678-a5c8-55cde9508821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;horiMargin10 vertMargin10&quot;]/form[1]/table[@class=&quot;table table-sm&quot;]/tbody[1]/tr[2]/td[@class=&quot;alignTop horiPad8 vertPad10&quot;]/table[@class=&quot;tableClps noBorder&quot;]/tbody[1]/tr[1]/td[2]/input[@class=&quot;solid1 height29 uppercase&quot;]</value>
      <webElementGuid>89d0edb6-ec51-4bac-8a9b-f70c31adf352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='bmsEdiId']</value>
      <webElementGuid>26077b10-b064-4c26-b3ca-f990db7b6c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>79cb2fe9-b577-4d61-9b1f-f892e4577574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bmsEdiId']</value>
      <webElementGuid>fe215d8c-b4db-4aa4-a474-09d9297c09cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
