<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Print</name>
   <tag></tag>
   <elementGuidId>8284c554-36fa-450b-8d94-962ff05ab731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='cmdPrint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;cmdPrint&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9507274f-1fd4-4726-baee-0a06574505c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmdPrint</value>
      <webElementGuid>9d8fe1f5-8d63-409e-acdc-921422a9061b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-sm button-info button-outline mr-xs</value>
      <webElementGuid>d7c82ee0-e00e-4b5c-9f3b-19e880a0f815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22cdcaa8-fcb1-4145-9ccc-24c30ca3fdec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>isPrint=true;check4('');</value>
      <webElementGuid>898bd274-f29e-4142-a1d1-00ce4cbe58e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			
          Print
        </value>
      <webElementGuid>6d194569-0163-4e1a-89ba-fc5fb24b13bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblReport&quot;)/tbody[1]/tr[61]/td[@class=&quot;alignRgt&quot;]/button[@class=&quot;button button-sm button-info button-outline mr-xs&quot;]</value>
      <webElementGuid>f985eda4-bd7b-4288-a50f-95c7a58c5d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Report/New_InvoiceRegisterReport/Page_/iframe_Eligibility_content</value>
      <webElementGuid>9afbf608-0de0-4eb0-98ab-bbab79954fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='cmdPrint']</value>
      <webElementGuid>1debbb5c-4e6b-4457-9521-ab0bf93240d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblReport']/tbody/tr[61]/td/button[3]</value>
      <webElementGuid>cd3297c5-2470-4d3f-aac3-7a68e3588ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>88100a3d-401c-4a47-93f0-3b06bbc92e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'cmdPrint' and @type = 'button' and (text() = '
			
          Print
        ' or . = '
			
          Print
        ')]</value>
      <webElementGuid>c30705d9-4af2-4c31-845c-cba631c40a3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
