<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_INVOICE REGISTER REPORT</name>
   <tag></tag>
   <elementGuidId>3dca86ca-1fdd-4aa8-ae87-0ff64497c9bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.page-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3f8046d4-39c7-4c16-93fa-a0a9b2b68ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-heading</value>
      <webElementGuid>04476979-f0ba-43d2-9dad-f85b61aabfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INVOICE REGISTER REPORT</value>
      <webElementGuid>c180498b-19ca-4a2b-a2f0-0ad7d46bdfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-lg bg-gray-lightest&quot;]/h1[@class=&quot;page-heading&quot;]</value>
      <webElementGuid>653be549-b0c6-44e7-91ab-eb25c42f98a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Report/New_InvoiceRegisterReport/Page_/iframe_Eligibility_content</value>
      <webElementGuid>26ecf9be-5ab2-4f84-bf38-8ad48cbecabf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>63259a2c-6e1b-4922-8498-3a37c555b99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'INVOICE REGISTER REPORT' or . = 'INVOICE REGISTER REPORT')]</value>
      <webElementGuid>19ba9a92-9161-42d8-9bb8-3abd7214d0a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
