<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_ALNY - HEALTH SYSTEM SERVICES - ALBANY</name>
   <tag></tag>
   <elementGuidId>caac7fd0-5979-4f45-ad59-b890a31f4924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='ALNY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;ALNY&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2b718cfd-d9a3-469c-ba3f-5ed46a3b79d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ALNY</value>
      <webElementGuid>2971d3e3-1ba8-4fb4-bd5f-f343a84e2b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALNY - HEALTH SYSTEM SERVICES - ALBANY</value>
      <webElementGuid>0e88aa7a-6e84-44bb-8ca6-76b51a81a311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblReport&quot;)/tbody[1]/tr[3]/td[2]/select[@class=&quot;input input-sm&quot;]/option[2]</value>
      <webElementGuid>cc794a62-0554-409a-b68f-8c9e6b025f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Report/New_InvoiceRegisterReport/Page_/iframe_Eligibility_content</value>
      <webElementGuid>dfa7ef77-4edd-4566-826b-89df98b494d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='ALNY']</value>
      <webElementGuid>418d28a2-d67a-4ea6-b932-37ea154a5a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblReport']/tbody/tr[3]/td[2]/select/option[2]</value>
      <webElementGuid>eabad49d-ba1d-47a8-a52e-a66e32d85371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//option[2]</value>
      <webElementGuid>308c47da-a4fd-402b-b99b-121bc13d887c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = 'ALNY - HEALTH SYSTEM SERVICES - ALBANY' or . = 'ALNY - HEALTH SYSTEM SERVICES - ALBANY')]</value>
      <webElementGuid>8a5367af-52db-4888-92c5-14a45969b4a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
