<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YesNo_NEW_CREATE_TASK_0</name>
   <tag></tag>
   <elementGuidId>ebc8c4de-5cb0-49f3-89d8-bf4c3ca7592b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NEW_CREATE_TASK_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;NEW_CREATE_TASK_0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b466438a-0b09-4ddc-835a-1cb9d5c66834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6951b4fe-8b18-4b53-b6e9-c8008c1d167b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>5f236d06-cc05-465a-85c8-d876772cd28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NEW_CREATE_TASK_0</value>
      <webElementGuid>25d394f2-78e1-48f9-90ba-e3091c47146a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl&quot;)/tbody[1]/tr[1]/td[@class=&quot;horiPad3 vertPad3 solidBlk1 ariBlkLft12&quot;]/div[1]/input[1]</value>
      <webElementGuid>65b95416-091f-4b07-8fe9-6fce8bfc229b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Data Setup/Page_/iframe_Eligibility_content</value>
      <webElementGuid>2f9c8786-1278-44c7-9c49-22b9702e224c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NEW_CREATE_TASK_0']</value>
      <webElementGuid>5ad86195-481e-4242-bfad-cee6c6106834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl']/tbody/tr/td[11]/div/input</value>
      <webElementGuid>ecdf1da6-90b9-492c-8af4-d23f64737b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/input</value>
      <webElementGuid>98174ffe-7105-45b3-935b-5647078e1813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NEW_CREATE_TASK_0']</value>
      <webElementGuid>75effd59-8432-4e6e-9b22-2918d4b999dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
