<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Days Between_NEW_STEPNO</name>
   <tag></tag>
   <elementGuidId>1f1a64a9-61e5-4559-a06e-c562e2fc1906</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NEW_STEPNO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;NEW_STEPNO&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbd1c6b8-5c5f-40f3-bfac-25dd20cfdb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>510d3868-3870-456b-a49b-09e7a4a139f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>be080ca3-23d7-410b-ac46-90b87af412fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input uppercase input-sm</value>
      <webElementGuid>530f4fe0-e865-4a1e-9cab-509970cb535d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NEW_STEPNO</value>
      <webElementGuid>038913c0-ba4f-44fe-aa44-f687091904f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>5a7c090a-4a21-42a3-8571-047ab23b763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>value=value.replace(/[^\d]/g,'')</value>
      <webElementGuid>3552bdf9-bf0f-4534-a304-70c46301fabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl&quot;)/tbody[1]/tr[1]/td[@class=&quot;horiPad3 vertPad3 solidBlk1 ariBlkLft12&quot;]/input[@class=&quot;input uppercase input-sm&quot;]</value>
      <webElementGuid>f1ce0323-84ad-4a5b-b921-fc0c2bef1f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Data Setup/Page_/iframe_Eligibility_content</value>
      <webElementGuid>f4abc3c0-efdc-4c48-b152-299671642f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NEW_STEPNO']</value>
      <webElementGuid>16ef8511-12ad-4493-80ac-16e92fbe357c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl']/tbody/tr/td/input</value>
      <webElementGuid>2620bd1e-6cc1-4619-8cf0-33f7c98d48a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>f1b5b886-5467-46aa-a16a-5291d9bc415a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NEW_STEPNO']</value>
      <webElementGuid>5d55d23c-049f-4ee9-9ea4-796a83119b46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
