<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New_NEW_DESCRIPTION</name>
   <tag></tag>
   <elementGuidId>658424c7-cc09-4407-a8f1-5c01aecb8ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NEW_DESCRIPTION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;NEW_DESCRIPTION&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2978df8-c65a-41a7-994f-6f97e3c3ae58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddf75c53-fa7a-42ea-8c4a-b11ee747ec4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>d0863fc6-9ab3-4ba6-afe9-95863cfa6767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input uppercase</value>
      <webElementGuid>406d1bd1-0db0-4448-8cd5-d5973616a067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NEW_DESCRIPTION</value>
      <webElementGuid>7a2151dd-ad47-4332-a3f2-9fb08f24876e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl&quot;)/tbody[1]/tr[32]/td[@class=&quot;solidBlk1&quot;]/input[@class=&quot;input uppercase&quot;]</value>
      <webElementGuid>fa556d86-7bc2-4032-880c-f738622f2816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Data Setup/Page_/iframe_Eligibility_content</value>
      <webElementGuid>46b65c5c-a368-4130-a293-da3eda0623c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NEW_DESCRIPTION']</value>
      <webElementGuid>7cb69a85-00f3-4ecb-839c-607d13ea2140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl']/tbody/tr[32]/td/input</value>
      <webElementGuid>068f2266-7962-41b9-a517-0f48397f79fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[32]/td/input</value>
      <webElementGuid>1e2e5dcb-aa70-4bc9-9c65-c84fcdc1bace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NEW_DESCRIPTION']</value>
      <webElementGuid>5d9d0398-b25f-4807-8df7-d15ec5a11e41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
